### ISSUE TITLE
css 居中总结

### ISSUE THREAD

**Issue by wanghuajian620** [wanghuajian620/wanghuajian620.github.io#3]
### 水平居中

1. 行内元素： `text-align: center`
2. 块级元素： `marin: 0 auto`
3. 多个块级元素： 如果页面里有多个块状元素需要水平排列居中，可以将元素的 `display` 属性设置为     `inline-block`，并且把父元素的 `text-align` 属性设置为 `center` 即可实现。

### 垂直居中

1. 单行的行内元素： 设置 `height` 等于 `line-height` 即可

```css
div { 
  height: 30px; 
  line-height: 30px; 
  overflow: hidden; 
}
```

2. 多行的行内元素——组合使用 `display:table-cell` 和 `vertical-align:middle` 属性来定义需要居中的元素的父容器元素

```css
.container {
  background: #222;
  width: 300px;
  height: 300px;
  /* 以下属性垂直居中 */
  display: table-cell;
  vertical-align:middle;
}
```

3. 块级元素——使用 `transform` 属性来垂直移动来实现垂直居中

```css
.container {
  top: 50%;
  position: absolute;
  transform: translateY(-50%); 
}
```

4. 还可以这样

```css
.container {
  width:300px;
  height: 300px;
  /* 以下属性垂直居中 */
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin: auto;
}
```

### 水平垂直居中

一般的行内/块级元素通过以上方法的简单组合即可实现水平垂直居中，下面介绍两个简单粗暴的方法：

1. flex 布局

```css
.container {
  display: flex;
  justify-content:center;
  align-items: center; 
  /* 注意这里需要设置高度来查看垂直居中效果 */
  background: #AAA;
  height: 200px;
}
```

2. transform 

```css
.container {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%);
}
```
